version: '3.8'

services:
  # PostgreSQL数据库
  db:
    image: postgres:15
    container_name: echopolis_db
    environment:
      POSTGRES_DB: echopolis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - echopolis_network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: echopolis_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - echopolis_network

  # 后端API服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: echopolis_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/echopolis
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=True
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs
    networks:
      - echopolis_network
    restart: unless-stopped

  # 前端Web服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: echopolis_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - echopolis_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  echopolis_network:
    driver: bridge